from __future__ import annotations

GRAY_18 = '#767676'
GRAY_0 = '#0d0d0d'
GRAY_1 = '#141414'
GRAY_2 = '#1e1e1e'
GRAY_3 = '#282828'
GRAY_4 = '#3a3a3a'

ACCENT_COLOR_TEXT = '#c8a96e'
ACCENT_COLOR_TEXT_SECONDARY = '#7ec8c8'
TEXT_DIM = '#888888'
TEXT_MAIN = '#d4d4d4'
TEXT_HI = '#f0f0f0'

FONT_WEIGHT_SEMIBOLD = 600
FONT_WEIGHT_BOLD = 700

# Layout rhythm
SIZE_TAB_STRIP_OFFSET = '0px'
SIZE_TAB_MARGIN_RIGHT = '2px'
SIZE_FORM_SPACING = '6px'
SIZE_CHECKBOX_SPACING = '8px'
SIZE_SPLITTER_HANDLE_WIDTH = '1px'
SIZE_SPLITTER_HANDLE_MARGIN_LEFT = '8px'
SIZE_SECTION_STACK_SPACING = '8px'

# Inline paddings
SIZE_CONTROL_PADDING = '3px 6px'
SIZE_BUTTON_PADDING = '0px 10px'
SIZE_HEADER_PADDING = '3px 8px'
SIZE_TAB_PADDING = '6px 10px'
SIZE_TOOLBUTTON_PADDING = '3px 6px'
SIZE_TOOLBUTTON_POPUP_PADDING_RIGHT = '2px'

# Heights and widths
SIZE_CONTROL_MIN_HEIGHT = '22px'
SIZE_COMPACT_BUTTON_MIN_HEIGHT = '22px'
SIZE_BUTTON_MIN_HEIGHT = '32px'
SIZE_FOOTER_MIN_HEIGHT = SIZE_BUTTON_MIN_HEIGHT
SIZE_SPIN_BUTTON_WIDTH = '14px'
SIZE_COMBO_DROPDOWN_WIDTH = '16px'
SIZE_CHECKBOX_INDICATOR = '15px'
SIZE_SCROLLBAR_HANDLE_MIN = '28px'

# Runtime layout metrics
SIZE_APP_MARGIN = 0
SIZE_PANEL_MARGIN = 10
SIZE_TAB_CONTENT_TOP_MARGIN = 12
SIZE_SECTION_FRAME_MARGIN = 8
SIZE_SECTION_FRAME_INDENT = 24
SIZE_FOOTER_ITEM_SPACING = 6
SIZE_FOOTER_TOP_SPACING = 8
SIZE_FOOTER_BOTTOM_INSET = 8

# Widget color definitions
BASE_BG = GRAY_0
PANEL_BG = GRAY_0
PANEL_BG_ACTIVE = GRAY_1
TAB_SELECTED_BG = GRAY_0
TAB_TEXT_ACCENT = ACCENT_COLOR_TEXT
CONTROL_BG = GRAY_2
CONTROL_BG_HOVER = GRAY_3
CONTROL_BG_PRESSED = GRAY_2
CONTROL_MENU_BG = GRAY_1
CONTROL_SELECTION_BG = GRAY_3
TEXT_SELECTION_BG = GRAY_4
HEADER_BG = GRAY_1
CHECKED_BG = GRAY_3
DISABLED_BG = GRAY_1
SCROLLBAR_HANDLE_BG = GRAY_3
SPLITTER_BG = GRAY_2
STATUS_BG = GRAY_1
BUTTON_ACCENT_BG = '#3a2e1a'
BUTTON_ACCENT_BG_HOVER = '#4a3a22'
BUTTON_ACCENT_BG_PRESSED = '#3a2e1a'
TEXT_PRIMARY = TEXT_MAIN
TEXT_SOFT = TEXT_DIM
TEXT_BRIGHT = TEXT_HI
TEXT_HEADER = TEXT_MAIN
TEXT_CONTROL = TEXT_MAIN
TEXT_HEADER_SECTION = TEXT_DIM
TEXT_ACCENT = ACCENT_COLOR_TEXT
TEXT_STATUS = TEXT_MAIN
HEADER_DIVIDER_LINE = GRAY_2
BOOL_EDITOR_HOVER_BG = GRAY_3
BOOL_EDITOR_FILL_ENABLED = GRAY_2
BOOL_EDITOR_FILL_DISABLED = GRAY_1
BOOL_EDITOR_CHECKED_ENABLED = GRAY_2
BOOL_EDITOR_CHECKED_DISABLED = GRAY_1
BOOL_EDITOR_BORDER_CHECKED = GRAY_0
BOOL_EDITOR_BORDER_UNCHECKED = GRAY_0
BOOL_EDITOR_CHECKMARK = ACCENT_COLOR_TEXT