"""
测试脚本：验证 ICC profile 生成逻辑
格式参考：Capture One 自己的 scnr class + Lab PCS + mft2 A2B0 LUT (33 grid)
"""
import struct
import numpy as np
import colour
import time

from spektrafilm.runtime.api import init_params, digest_params
from spektrafilm.runtime.process import Simulator


def rgb_to_lab_d50(rgb_linear):
    """线性 sRGB → CIE Lab (D50 白点)，用于 ICC mft2 编码"""
    # sRGB primaries → XYZ D65
    xyz_d65 = colour.RGB_to_XYZ(
        rgb_linear,
        colourspace=colour.RGB_COLOURSPACES['sRGB'],
        illuminant=colour.CCS_ILLUMINANTS['CIE 1931 2 Degree Standard Observer']['D65'],
        chromatic_adaptation_transform='Bradford',
    )
    # XYZ D65 → XYZ D50 (Bradford)
    xyz_d50 = colour.adaptation.chromatic_adaptation_VonKries(
        xyz_d65,
        colour.xy_to_XYZ(colour.CCS_ILLUMINANTS['CIE 1931 2 Degree Standard Observer']['D65']),
        colour.xy_to_XYZ(colour.CCS_ILLUMINANTS['CIE 1931 2 Degree Standard Observer']['D50']),
        transform='Bradford',
    )
    # XYZ D50 → Lab
    lab = colour.XYZ_to_Lab(
        xyz_d50,
        illuminant=colour.CCS_ILLUMINANTS['CIE 1931 2 Degree Standard Observer']['D50'],
    )
    return lab


def build_icc_mft2(lut_data_lab, grid_size=33, profile_name='spektrafilm'):
    """
    构建 ICC v2 profile，scnr class，Lab PCS，mft2 A2B0 LUT。
    lut_data_lab: (grid^3, 3) float array，Lab 值，L in [0,100], a/b in [-128,127]
    """
    n = grid_size
    assert lut_data_lab.shape == (n**3, 3)

    # mft2 tag: 3 in, 3 out, grid_size grid points
    # Format: sig(4) + reserved(4) + in_ch(1) + out_ch(1) + grid(1) + in_table_entries(1)
    #         + matrix(9*4) + in_table(in_ch * entries * 2) + clut(grid^3 * out_ch * 2) + out_table(...)
    # Simplified: no input/output curves (identity = single entry 0x0000 and 0xFFFF)

    in_ch = 3
    out_ch = 3
    in_entries = 2   # identity curve: [0, 65535]
    out_entries = 2  # identity curve: [0, 65535]

    # Identity matrix (3x3, s15Fixed16)
    identity_matrix = [
        1.0, 0.0, 0.0,
        0.0, 1.0, 0.0,
        0.0, 0.0, 1.0,
    ]

    # Encode Lab to uint16
    # ICC Lab encoding: L* = L/100 * 65535, a* = (a+128)/255 * 65535, b* = (b+128)/255 * 65535
    L = np.clip(lut_data_lab[:, 0], 0, 100)
    a = np.clip(lut_data_lab[:, 1], -128, 127)
    b = np.clip(lut_data_lab[:, 2], -128, 127)
    L_enc = np.round(L / 100.0 * 65535).astype(np.uint16)
    a_enc = np.round((a + 128.0) / 255.0 * 65535).astype(np.uint16)
    b_enc = np.round((b + 128.0) / 255.0 * 65535).astype(np.uint16)
    clut_uint16 = np.stack([L_enc, a_enc, b_enc], axis=1)  # (n^3, 3)

    # Build mft2 binary
    mft2 = bytearray()
    mft2 += b'mft2'          # type signature
    mft2 += b'\x00\x00\x00\x00'  # reserved
    mft2 += bytes([in_ch, out_ch, n, 0])  # channels + grid + padding
    # Matrix (9 x s15Fixed16)
    for v in identity_matrix:
        mft2 += struct.pack('>i', int(round(v * 65536)))
    # in_table_entries count (uint16 per channel)
    mft2 += struct.pack('>H', in_entries)
    mft2 += struct.pack('>H', out_entries)
    # Input tables: identity (2 entries per channel)
    for _ in range(in_ch):
        mft2 += struct.pack('>H', 0)
        mft2 += struct.pack('>H', 65535)
    # CLUT
    for row in clut_uint16:
        for val in row:
            mft2 += struct.pack('>H', int(val))
    # Output tables: identity
    for _ in range(out_ch):
        mft2 += struct.pack('>H', 0)
        mft2 += struct.pack('>H', 65535)

    # Pad to 4-byte boundary
    while len(mft2) % 4 != 0:
        mft2 += b'\x00'

    mft2 = bytes(mft2)

    # Build ICC profile
    # Tags: desc, cprt, wtpt, A2B0, tech
    def make_text_tag(text):
        encoded = text.encode('ascii', errors='replace')
        tag = b'text' + b'\x00\x00\x00\x00' + encoded + b'\x00'
        while len(tag) % 4 != 0:
            tag += b'\x00'
        return tag

    def make_desc_tag(text):
        # ICC v2 'desc' tag
        encoded = text.encode('ascii', errors='replace') + b'\x00'
        tag = b'desc' + b'\x00\x00\x00\x00'
        tag += struct.pack('>I', len(encoded))
        tag += encoded
        while len(tag) % 4 != 0:
            tag += b'\x00'
        return tag

    def make_xyz_tag(x, y, z):
        tag = b'XYZ ' + b'\x00\x00\x00\x00'
        tag += struct.pack('>i', int(round(x * 65536)))
        tag += struct.pack('>i', int(round(y * 65536)))
        tag += struct.pack('>i', int(round(z * 65536)))
        return tag

    def make_tech_tag():
        # 'tech' tag: technology signature, 'fscn' = film scanner
        tag = b'sig ' + b'\x00\x00\x00\x00' + b'fscn'
        return tag

    desc_data = make_desc_tag(profile_name)
    cprt_data = make_text_tag('Generated by spektrafilm')
    wtpt_data = make_xyz_tag(0.9642, 1.0000, 0.8249)  # D50
    tech_data = make_tech_tag()

    # Tag table
    tag_list = [
        (b'desc', desc_data),
        (b'cprt', cprt_data),
        (b'wtpt', wtpt_data),
        (b'A2B0', mft2),
        (b'tech', tech_data),
    ]

    # Calculate offsets
    header_size = 128
    tag_table_size = 4 + len(tag_list) * 12  # count + entries
    current_offset = header_size + tag_table_size

    tag_offsets = []
    tag_data_blocks = []
    for sig, data in tag_list:
        tag_offsets.append(current_offset)
        tag_data_blocks.append(data)
        current_offset += len(data)

    total_size = current_offset

    # Build header (128 bytes)
    header = bytearray(128)
    struct.pack_into('>I', header, 0, total_size)       # profile size
    header[4:8] = b'appl'                               # preferred CMM
    struct.pack_into('>I', header, 8, 0x02100000)       # version 2.1
    header[12:16] = b'scnr'                             # device class: scanner/input
    header[16:20] = b'RGB '                             # color space
    header[20:24] = b'Lab '                             # PCS: Lab
    # creation date/time (zeros = unspecified)
    header[36:40] = b'acsp'                             # signature
    header[40:44] = b'APPL'                             # platform
    # flags, manufacturer, model, attributes = 0
    struct.pack_into('>I', header, 64, 0)               # rendering intent: perceptual
    # PCS illuminant: D50 XYZ
    struct.pack_into('>i', header, 68, int(0.9642 * 65536))
    struct.pack_into('>i', header, 72, int(1.0000 * 65536))
    struct.pack_into('>i', header, 76, int(0.8249 * 65536))
    header[80:84] = b'argl'                             # profile creator

    # Build tag table
    tag_table = bytearray()
    tag_table += struct.pack('>I', len(tag_list))
    for i, (sig, _) in enumerate(tag_list):
        tag_table += sig
        tag_table += struct.pack('>I', tag_offsets[i])
        tag_table += struct.pack('>I', len(tag_data_blocks[i]))

    # Assemble
    profile = bytes(header) + bytes(tag_table)
    for block in tag_data_blocks:
        profile += block

    return profile


def generate_icc_for_state(sim, profile_name='spektrafilm', grid_size=33):
    """用 Simulator 生成 ICC profile bytes"""
    n = grid_size
    steps = np.linspace(0, 1, n)
    # meshgrid: R varies fastest (ICC mft2 convention: last channel varies fastest)
    b_g, g_g, r_g = np.meshgrid(steps, steps, steps, indexing='ij')
    # ICC A2B0 input order: R, G, B — R varies slowest, B fastest
    r_g2, g_g2, b_g2 = np.meshgrid(steps, steps, steps, indexing='ij')
    grid = np.stack([r_g2.ravel(), g_g2.ravel(), b_g2.ravel()], axis=1)

    total = n**3
    side = int(np.ceil(np.sqrt(total)))
    padded = np.zeros((side * side, 3), dtype=np.float64)
    padded[:total] = grid
    img = padded.reshape(side, side, 3)

    out = sim.process(img)
    out_flat = out.reshape(-1, 3)[:total]
    out_flat = np.clip(out_flat, 0, 1)

    # sRGB linear → Lab D50
    lab = rgb_to_lab_d50(out_flat)

    return build_icc_mft2(lab, grid_size=n, profile_name=profile_name)


# ── Test ──────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    print('Building simulator...')
    params = init_params(film_profile='kodak_gold_200', print_profile='kodak_supra_endura')
    params.settings.use_enlarger_lut = True
    params.settings.use_scanner_lut = True
    params.settings.lut_resolution = 17
    params.settings.use_fast_stats = True
    params.film_render.grain.active = False
    digested = digest_params(params)
    sim = Simulator(digested)

    print('Generating ICC...')
    t0 = time.time()
    icc_bytes = generate_icc_for_state(sim, profile_name='spektrafilm_kodak_gold_200')
    print('Done in', round(time.time() - t0, 2), 's,', len(icc_bytes), 'bytes')

    out_path = 'scripts/spektrafilm_test.icc'
    with open(out_path, 'wb') as f:
        f.write(icc_bytes)
    print('Written to', out_path)

    # Verify structure
    print()
    print('Verifying structure:')
    import struct as _s
    d = icc_bytes
    print('  Size field:', _s.unpack_from('>I', d, 0)[0], '== actual:', len(d))
    print('  Device class:', d[12:16])
    print('  Color space:', d[16:20])
    print('  PCS:', d[20:24])
    tag_count = _s.unpack_from('>I', d, 128)[0]
    print('  Tag count:', tag_count)
    for i in range(tag_count):
        off = 132 + i * 12
        sig = d[off:off+4]
        t_off = _s.unpack_from('>I', d, off+4)[0]
        t_sz = _s.unpack_from('>I', d, off+8)[0]
        print('   ', sig, 'offset:', t_off, 'size:', t_sz)
